### ISSUE TITLE
System user does not work does not work in .NET 6.0

### ISSUE THREAD

**Issue by andreas-nkb** [SuperOffice/SuperOffice.WebApi-Samples#13]
Hi,

Were are trying to authenticate with a system user in a .net 6.0 project but get the following error.

`TypeLoadException: Could not load type 'Microsoft.IdentityModel.JsonWebTokens.TokenValidationResult' from assembly 'Microsoft.IdentityModel.JsonWebTokens, Version=6.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
SuperOffice.WebApi.IdentityModel.SystemUserClient.GetSystemUserTicketAsync()`

We are dependent on version 6.10 for another nuget, which means we can not downgrade the `Microsoft.IdentityModel.JsonWebTokens` package.

Would it be possible to add support for NET 6.0? 

/Andreas

**Comment by SuperOfficeDevNet** [comment]
Hi Andreas, 

We are investigating bumping Microsoft.IdenrityModel.* libraries to more recent nuget versions. 

That said, are you confused in thinking that NET 6.0 doesn't support NET Standard 2.0 libraries? .NET 6 does consume NET Standard libraries, but yes, some of our package dependencies are older - but aren't runtime specific.

**Comment by stonesvillage** [comment]
Hi,

Yes - we're aware of that NET 6.0 supports NET Standard 2.0 libraries.

I think the problem here is that the WebApi agents package have dependencies to Microsoft.IdentityModel.* v5.6.0 or _higher_ (>= 5.6.0).
That means that it will use Microsoft.IdentityModel.* v6.10.0.0 which comes with .NET 6.0.
Some breaking change in the newer package probably result in the TypeLoadException.

Are you guys have a workaround for this while we're waiting for the bump to a more recent nuget version?

Best regards

Gunnar Stensby

**Comment by stonesvillage** [comment]
Hi,

Any updates here or should we look into fixing it on our side if you guys have other priorities right now?

**Comment by SuperOfficeDevNet** [comment]
OK. We have concluded the best course of action will be to extract the SystemUserClient from the SuperOffice.WebApi library and open source and publish a new package called SuperOffice.SystemUser.Client. The source code for this package will be available in the [SuperOffice.SystemUser.Client](https://github.com/SuperOffice/SuperOffice.SystemUser.Client) repo.

I expect the code to be pushed to the repo by the end of today. The nuget package will be configured and pushed by a github workflow sometime after.

**Comment by AnthonyYates** [comment]
The [SuperOffice.SystemUser.Client](https://github.com/SuperOffice/SuperOffice.SystemUser.Client) repo is live. A nuget package from SuperOffice will be come in the near future.

**Comment by SuperOfficeDevNet** [comment]
We must add that there is one breaking change:

* The Environment enum has been removed in favor of a string.
* The Environment property is replaced with SubDomain string, and can be "sod", "qastage" or "online"

We hope this is more intuitive. Any feedback is appreciated.

**Comment by stonesvillage** [comment]
Hi,

Great news, really appreciate this!

Gunnar Stensby, i-Centrum AB

**Comment by SuperOfficeDevNet** [comment]
The nuget package is published. Granted, the SystemUserInfo class in this library will obviously not be compatible with the one in SuperOffice.WebApi, but we are working on solving that side of it next.

Consider this issue closed.
