### ISSUE TITLE
RequestOptions is optional when using agents but System.NullReferenceException is thrown if RequestOptions isn't specified

### ISSUE THREAD

**Issue by stonesvillage** [SuperOffice/SuperOffice.WebApi-Samples#15]
Hi,

Just upgraded to latest version (10.1.3.669) of the WebApi package.
We get errors on every use of agents when RequestOptions isn't specified.
Ex throwing `System.NullReferenceException`:
`var contact = await contactAgent.GetContactEntityAsync(1);`

Stacktrace: 
` at SuperOffice.WebApi.Agents.AgentBase.Merge(RequestOptions options)`

Workaround is to always specify the _optional_ RequestOptions parameter:
`var contact = await contactAgent.GetContactEntityAsync(1, new RequestOptions());`

I would consider this a bug since the RequestOptions parameter is optional, but is required by internal logic.

Best regards

Gunnar Stensby, i-Centrum AB

**Comment by SuperOfficeDevNet** [comment]
Hi Gunnar,

Not sure how this slipped through, the samples and tests were working prior to pushing so I need to look into this ASAP... 

Will try to get a new working one out soon.

**Comment by stonesvillage** [comment]
Great news, thank you Tony!

**Comment by SuperOfficeDevNet** [comment]
OK, the latest packages (10.1.4.104) pushed this morning should address the RequestOptions issue.
