### ISSUE TITLE
SubDomain constant holds wrong subdomin for stage

### ISSUE THREAD

**Issue by andreas-nkb** [SuperOffice/SuperOffice.WebApi-Samples#16]
Hi!

So we are using the `SuperOffice.WebApi.SubDomain` class for mapping between `AspNet.Security.OAuth.SuperOffice.SuperOfficeAuthenticationEnvironment` and environment subdomain. 

The `public const string Stage` hold the value "qastage". Should it not be "qaonline"?

EDIT: Looks like the subdomain is validated when calling GetTenantStatusAsync() so manually changing to "qaonline" does not work either..
`System.ArgumentOutOfRangeException: Specified an invalid subdomain. Are you targeting the correct online subdomain? (Parameter 'subdomain')
at SuperOffice.WebApi.Authorization.Utility.UrlHelper..ctor(String subdomain)
at SuperOffice.WebApi.Agents.ApiAgent.GetTenantStatusAsync(String tenantCustId, String subdomain, RequestOptions requestOptions)
at`

/Andreas

**Comment by stonesvillage** [comment]
Hi,

Any input on this?
We're trying to get one of our new apps to review but are unable to do that until this issue in stage is resolved.

Best regards
Gunnar Stensby

**Comment by SuperOfficeDevNet** [comment]
Hi! Not good. We'll fix this.

**Comment by SuperOfficeDevNet** [comment]
Merge into 10.1.5 release branch, Will publish a new package within 24 hours.
