### ISSUE TITLE
Version conflict when trying to upgrade to latest versions (10.1.5.2030)

### ISSUE THREAD

**Issue by stonesvillage** [SuperOffice/SuperOffice.WebApi-Samples#17]
Hi,
We get version conflicts when trying to upgrade to latest version (10.1.5.2030) of the `SuperOffice.WebAp`i packages:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/32515807/191676079-553a0a35-eb25-4c97-9508-57d335a22eb7.png">

Package `SuperOffice.WebApi` has a specific version range (why?) for package `Microsoft.Extensions.Logging.Abstractions` (>=2.1.1 && < 2.2.0):
<img width="277" alt="image" src="https://user-images.githubusercontent.com/32515807/191676854-77e70bbb-1a00-474e-a38b-54c0686e6864.png">
The version range was introduced in version 10.1.5.2026 from what I can see.

Since we're using the `SuperOffice.WebApi.Authorization.SystemUserTicket` package we have a dependency on `SuperOffice.SystemUser.Client` which has these dependencies:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/32515807/191677292-a2f790e3-8b98-42c0-8574-688e4c1fed2a.png">
Package `Microsoft.Extensions.Caching.Memory` has a dependency on `Microsoft.Extensions.Logging.Abstractions` (>= 6.0.0) and here's the conflict:
- ` SuperOffice.WebApi: Microsoft.Extensions.Logging.Abstractions` (>=2.1.1 && < 2.2.0)
- `SuperOffice.SystemUser.Client: Microsoft.Extensions.Caching.Memory` (>=6.0.1) -> `Microsoft.Extensions.Logging.Abstractions` (>= 6.0.0)

Best regards

Gunnar Stensby, i-Centrum AB

**Comment by SuperOfficeDevNet** [comment]
Thanks, for letting me know. The 10.1.6 branch has the fix, and I thought that was back-ported, but apparently not. 

Use the previous version which shouldn't contain this problem. There are no real changes - except in NetServer - which this doesn't depend, and therefore this probably shouldn't have been pushed.

**Comment by undefined7fh** [comment]
Hi @SuperOfficeDevNet , could you please let us know when the new version of 10.1.6 branch will appear?
I saw it was a new package released - 10.1.5.2030, but on the next day it was removed from nuget.org due to security issues.

**Comment by SuperOfficeDevNet** [comment]
Pushed v10.1.6.807. New changes are listed on the nuget readme page.
