### ISSUE TITLE
ForeignKey.Value contains corrupt json when using ForeignSystemAgent.GetDeviceKeysAsync with RequestOptions where LanguageCode has a value

### ISSUE THREAD

**Issue by stonesvillage** [SuperOffice/SuperOffice.WebApi-Samples#18]
Hi,
We're using the FK system to store application settings as a json value:
```c#
var foreignKey = new ForeignKey
{
    Key = "myKey"
    Value = JsonConvert.SerializeObject(mySetting)
};
await foreignSystemAgent.SaveForeignKeyAsync(foreignKey, "myAppName", "myDeviceName",  "myDeviceId");
```

When getting the value the json is corrupt if `RequestOptions.LanguageCode` has a value:
```c#
var json = (await foreignSystemAgent.GetDeviceKeysAsync("myAppName", "myDeviceName", new RequestOptions { LanguageCode="EN"})).First().Value; // corrupt
var mySetting = JsonConvert.DeserializeObject<MySetting>(json); // fails due to corrupt json
```

Workaround is to not specify `RequestOptions`.

In our case we have a default `WebApiOptions` with `LanguageCode = "EN"` that is always specified when creating the agents, that's why we ran into this problem. Specifying a `RequestOptions` without setting the `LanguageCode` will make the json not to be corrupt, so we use that as a workaround at the moment.

BR

Gunnar Stensby, i-Centrum AB

**Comment by SuperOfficeDevNet** [comment]
Hi Gunnar,

I'm unable to reproduce any serialization error using 10.4.1 or 10.1.6.807 using the two following code examples.

![image](https://user-images.githubusercontent.com/15157161/201892062-768501be-8d4a-4d5a-8168-ef1960f00223.png)

or

![image](https://user-images.githubusercontent.com/15157161/201891372-b7c75e59-1d3b-4119-97f4-8885922b6623.png)

Maybe there is a problem in the key content itself?

**Comment by stonesvillage** [comment]
Hi,

Cannot see that the test verifies storing a json value and then deserialize it to a custom type.
The json is corrupt when a language code is specified, otherwise it is ok.

**Comment by SuperOfficeDevNet** [comment]
Tried it both ways, setting config language settings, and new RequestOptions, still unable to reproduce... SHouldn't matter, but how complex is your settings class? Maybe share that...

![image](https://user-images.githubusercontent.com/15157161/201949041-f7ce1cb6-45c6-413f-a08e-a01fa4d1c9d2.png)

**Comment by stonesvillage** [comment]
From what I can see the Value property doesn't contain valid json. Looks strange at "NamTest".

**Comment by xt1** [comment]
When you specify a language code, then we parse multi language strings in the response so that you get the right language value back.

So if the Json value contains something that looks like a multi language string: `"en":"blah";"no":"blæ"` then that will probably get parsed, resulting in corrupted Json.
We can probably fix the parser to recognize Json values and avoid trying to multi-lang parse them.

**Comment by SuperOfficeDevNet** [comment]
Bug reports go to sdk@superoffice.com or appdev@superoffice.com.

> From what I can see the Value property doesn't contain valid json. Looks strange at "NamTest". But I will post a full example soon.

Things go faster when you are able to submit a comprehensive example to reproduce a problem. 

This issue has nothing to do with the repo or samples.
