### ISSUE TITLE
Add Constants for archive provider names.

### ISSUE THREAD

**Issue by AnthonyYates** [SuperOffice/SuperOffice.WebApi-Samples#3]
Suggestion came in via sdk ticket request: 

> Only thing I am missing is some kind of constants list with all the available Archive providers. Currently when using the the SuperOffice.NetServer.Services package we reference the name of archive providers like this:

> __SuperOffice.CRM.ArchiveLists.FindAppointmentProvider.ProviderName__
> Or
> __SuperOffice.CRM.ArchiveLists.DotSyntaxProvider.ProviderName__

>Prevents you from making mistakes, and that is one ‘magic string’ less in the code 😊

**Comment by SuperOfficeDevNet** [comment]
Can use the following to create your own constants list:

```csharp
using (ArchiveAgent aa = new ArchiveAgent(config))
{
    var providerNames = await aa.GetProviderNamesAsync();
}
```
