### ISSUE TITLE
Unable to return data using the archive agent

### ISSUE THREAD

**Issue by RhodriBlackwellIB** [SuperOffice/SuperOffice.WebApi-Samples#5]
Hi,

I am trying to use the web api to get data using an archive agent however everything I try returns an empty ArchiveListItem array. This is happening with access token and system user token auth. I am able to use other agents without any issues.

`                ArchiveAgent archiveAgent = new ArchiveAgent(webApiOptions);

                var test1 = archiveAgent.GetArchiveListByColumns2Async("Person", "personId", "", "person = 1", "", 0, 100).Result;

                string searchEntity = "person";
                string[] columns = new[] { "personId" };
                var test2 = archiveAgent.GetArchiveListByColumnsAsync(
                    "Person",
                    columns,
                    new[]
                    {
                        new ArchiveOrderByInfo()
                        {
                            Name = columns[0],
                            Direction = OrderBySortType.ASC
                        }
                    },
                    new[]
                    {
                        new ArchiveRestrictionInfo()
                        {
                            Name = "personId",
                            Operator = "=",
                            Values = new [] {  "1" }
                        }
                    },
                    new[] { searchEntity },
                    0,
                    1).Result;`

Thanks,
Rhodri

**Comment by xt1** [comment]
Test 1 fails to produce any matches because the column 'person' does not
exist. Also we start numbering at id 2, so id 1 will not match anything.

var test1 = archiveAgent.GetArchiveListByColumns2Async("Person",
"personId,fullName", "", "personId = 2", "", 0, 100).Result;

Test 2 fails because id1 does not exist.

**Comment by RhodriBlackwellIB** [comment]
My mistake with the person column.

When you say numbering starts at id 2 do you mean in SuperOffice generally or in this particular area? I know I have a person entry with Id 1.

In any case, I still get the same result using the code snippet you provided.

In any case, I still get the same result using the code snippet you provided.

                        PersonAgent personAgent = new PersonAgent(webApiOptions);
                        var person = personAgent.GetPersonAsync(2).Result;

                        ArchiveAgent archiveAgent = new ArchiveAgent(webApiOptions);
                        var test1 = archiveAgent.GetArchiveListByColumns2Async("Person", "personId,fullName", "", "personId = 2", "", 0, 100).Result;`

The person agent returns a person as expected but nothing from the archive agent.

Thanks

**Comment by AnthonyYates** [comment]
You could also verify that person exists by navigating to that person page in SuperOffice:
https://sod.superoffice.com/Cust00000/default.aspx?person.main.projectarchive?person_id=1

If the person exists that, yes you should be able to get it via the archive API as well.

**Comment by RhodriBlackwellIB** [comment]
I can see people for id 1 and 2 by navigating to the URL in SuperOffice.

**Comment by RhodriBlackwellIB** [comment]
It turns out that it is the lack of entity being passed in causing the issue. The code below works as expected.

`var test1 = archiveAgent.GetArchiveListByColumns2Async("Person", "personId,fullName", "person", "personId = 2", "", 0, 100).Result`
