### ISSUE TITLE
ApiAgent.GetApiVersionAsync throws WebApiException

### ISSUE THREAD

**Issue by Jonas-Degn** [SuperOffice/SuperOffice.WebApi-Samples#6]
Hey there,

I am trying this new SDK out and most things are working absolutely wonderful, but it seems the `ApiAgent.GetApiVersionAsync` is broken. (using 1.0.0-preview3)
It will crash with an exception `[WebApiException: Forbidden Forbidden]`.

See example code:
```C#
// Any other agent works fine
using var personAgent = new PersonAgent(Context.Config);
var myPerson = await personAgent.GetMyPersonAsync();

using var apiAgent = new ApiAgent(Context.Config);

// Tenant status works fine
var tenantStatus = await apiAgent.GetTenantStatusAsync("Cust26135", Context.Tenant.Environment.Current);

// This one crashes
var apiVersion = await apiAgent.GetApiVersionAsync();

// Manual GET instead of using the agent also works fine
var restClient = new RestClient(Context.Tenant.WebApiUrl);
var restRequest = new RestRequest("", Method.GET);
var restResponse = await restClient.ExecuteAsync(restRequest);
```

**Comment by SuperOfficeDevNet** [comment]
Hi Jonas! 

I'm not able to reproduce your results. Would you be so kind as to elaborate on your WebApiOptions (Context.Config?) ? 

As seen in the examples, this works just fine for me...

```C#
WebApiOptions session = new WebApiOptions(tenant.WebApiUrl);

// no authorization necessary for getting system info...

var agent = new ApiAgent(session);
return await agent.GetApiVersionAsync();
```

**Comment by Jonas-Degn** [comment]
Yes of course.

You are in fact correct that the example provided works, but as soon as you add an `AuthorizationAccessToken` to the `WebApiOptions` then it breaks.

This fails:
```
Context.Config = new WebApiOptions(Context.Tenant.WebApiUrl)
  {
      Authorization = new AuthorizationAccessToken(
      oauthModel.AccessToken,
      oauthModel.IdToken,
      oauthModel.RefreshToken,
      Context.Application.ClientId,
      Context.Application.ClientSecret,
      Context.Application.RedirectUri.OriginalString,
      Context.Tenant.Environment.Current
      )
  };
```

This works:
```
Context.Config = new WebApiOptions(Context.Tenant.WebApiUrl);
```

I am aware that the ApiAgent does not require the user to be authorized, but it certainly shouldn't fail if such extra data is provided.

**Comment by SuperOfficeDevNet** [comment]
Hi Jonas!

Ok, yeah that's kinda of what I suspected but needed confirmation to be sure. I'm going to tag this as a bug and hope we get to it early next week. :bug:

Thanks for reporting this! 
:ambulance:

**Comment by xt1** [comment]
Fixed - we make sure to clear the auth header for GetApiVersionAsync call.
It's cleared from the clone of the settings we use for the call, so it does not affect the options object, only this call.
