### ISSUE TITLE
SystemUserClient.ValidateSystemUserResult deadlock

### ISSUE THREAD

**Issue by Jonas-Degn** [SuperOffice/SuperOffice.WebApi-Samples#7]
Hey there,

I have run into another issue.

My example is as follows:
```C#
var systemUserInfo = new SystemUserInfo()
{
    ClientSecret = Context.Application.ClientSecret,
    ContextIdentifier = Context.Tenant.ContextIdentifier,
    PrivateKey = Context.Application.PrivateKey,
    SystemUserToken = Context.User.SystemUserToken,
    Environment = Context.Tenant.Environment.Current
};
var systemUserClient = new SystemUserClient(systemUserInfo);

var validationAttempt1 = systemUserClient.GetSystemUserTicket(); 

var sysJwtToken = systemUserClient.GetSystemUserJwt();
var validationAttempt2 = systemUserClient.ValidateSystemUserResult(sysJwtToken);

var handler = new JwtTokenHandler(
Context.Application.ClientId,
new System.Net.Http.HttpClient(),
Context.Tenant.Environment.Current
);
var validationAttempt3 = handler.ValidateAsync(sysJwtToken.Token).GetAwaiter().GetResult();

var validationAttempt4 = System.Threading.Tasks.Task.Run(async () => await handler.ValidateAsync(sysJwtToken.Token)).GetAwaiter().GetResult();
            
```

First 3 of these validation attempts causes deadlock in my application, and since I don't know the underlying code, all I can do is guess about the cause.

Attempt 1 uses the built-in all-in-1 function that does everything - deadlocks.
Attempt 2 uses the underlying `ValidateSystemUserResult` and as such is expected to behave the same as `GetSystemUserTicket`, and it does the same - deadlock.
Attempt 3 does a manual validation using the example provided in the README - again deadlock.
Actually that is not entirely true, the README example does not await the async method, but it should.

Attempt 4 is my preferred way of running async code in sync context, and that does not deadlock which is nice...
But then it complains that the `ValidAudience` failed validation.

So I guess this is 2 bugs.
First issue being `SystemUserClient.ValidateSystemUserResult` deadlocking (presumably due to issues with running async validation in a sync context).
Second issue being even if it does run, then it fails validation due to invalid `ValidAudience`.

The ValidAudience in this case should be the app `client_id`, which I already use to manually validate the OAUTH `IdToken` - and that works fine.

I can bypass the deadlock manually for the time being (until a preview-4), but I was hoping you could help me find a solution to the invalid `ValidAudience` so I can move on with the implementation :)

**Comment by SuperOfficeDevNet** [comment]
Hi Jonas,

The examples in this repo work [on my machine] without any deadlocking issues. 

What type of environmental factors need to be created to reproduce deadlocking for validationAttempt1 and validationAttempt2? 

With regards to ValidAudience... The OAuth/OIDC ValidAudience is __NOT__ the same as the SystemUser ValidAudience. There are two different built in TokenHandlers to handle that difference; JwtTokenHandler and SystemUserTokenHandler. Therefore, to manually validate the systemuser result correctly, use the SystemUserTokenHandler.

> The README does were wrong and have been updated to reflect the following.

```c#
var systemUserClient = new SystemUserClient(systemUserInfo);
var sysJwtToken = systemUserClient.GetSystemUserJwt();

var handler = new SystemUserTokenHandler(
  new System.Net.Http.HttpClient(),
  Context.Tenant.Environment.Current
);
var validationAttempt3 = handler.ValidateAsync(sysJwtToken.Token).Result;
```

FYI, the different ValidAudience values are:

* OAuth/OIDC: validationParameters.ValidAudience = {{client_id}};
* SystemUser: validationParameters.ValidAudience = "spn:{{serial}}"; 
  * where {{serial}} is the serial claim is from the JWT claims collection

**Comment by Jonas-Degn** [comment]
Thank you for the updated README, using the correct token handler works wonderfully, and I can move on with our implementation 😄 

Regarding the deadlock, we are using `ASP.NET Web Application (.NET Framework)` straight out of Visual Studio, and we are using `.NET Framework 4.7.2` due to bottlenecks in our architecture preventing us from targeting 4.8.
`.NET Core 3 / .NET 5` is out of the question, we are simply not able to facilitate that with our current architecture.

Using `handler.ValidateAsync(sysJwtToken.Token).Result` will deadlock just as using `.GetAwaiter().GetResult()` (they do the same underneath), I just prefer the latter as you get the original exception instead of an `AggregateException` if anything goes wrong.

`System.Net.Http.HttpClient` is specifically known for causing such deadlocks when using `.Result` or `.GetAwaiter().GetResult()` and if you are doing so underneath the `SystemUserClient.ValidateSystemUserResult` then that explains it perfectly.
I would strongly advice to use `System.Threading.Tasks.Task.Run(async () => await HttpClientStuff)` as shown in validationAttempt4 to prevent such deadlocks.

**Comment by Jonas-Degn** [comment]
I have just confirmed that running `SystemUserClient.GetSystemUserTicket` inside a `System.Threading.Tasks.Task.Run` works just fine in my project.
I am pretty confident that the issue relates to the `HttpClient` running something async underneath which can cause deadlocks when running in a synchronized context like ASP.NET MVC (framework, not core).

**Comment by SuperOfficeDevNet** [comment]
Hi @Jonas-Degn ,

Yes, the HttpClient is used asynchronously to get the public SuperOffice certificate for validation (from the OAuth metadata endpoint), using the ConfigurationAgent. 

The world has moved on to Async everywhere and as such all agents use the HttpClient asynchronously. This behavior will not change.

As you have shown, and as [Microsoft has documented](https://docs.microsoft.com/en-us/previous-versions/aspnet/ee728598(v=vs.100)), there are ways to lift up legacy synchronous context bound applications to function in the current standard of a-synchronicity. Some [great tips here on SO](https://stackoverflow.com/questions/5095183/how-would-i-run-an-async-taskt-method-synchronously) as well.
