### ISSUE TITLE
Roadmap / plan

### ISSUE THREAD

**Issue by acdavidh** [SuperOffice/SuperOffice.WebApi-Samples#9]
Hi,

Is there any roadmap / plan / idea about the future of this library? 

We use it a lot in new applications and converted a few existing one's since we notice that the WebApi performs faster then the SOAP library (less data going over the wire), next to that the WebApi library doesn't carry the whole SuperOffice SDK and dependencies with it, causing a lot less conflicts.

Currently the last release, preview3, was 6 months ago. Any indication for a 'stable' release with the latest API additions?

**Comment by stonesvillage** [comment]
Hi,

We at i-Centrum are also interested in the roadmap of future releases and when the 1.0.0 release is planned.

Regards

**Comment by SuperOfficeDevNet** [comment]
I believe this issue has been answered [on the docs](https://docs.superoffice.com/api/netserver/web-services/proxies/index.html).

This library is meant as a preplacement for SuperOffice.NetServer.Services, and all future investment in web services API will be with SuperOffice.WebApi.
